---
- name: download the bloody intel firmware
  get_url: url=http://wireless.kernel.org/en/users/Drivers/iwlwifi?action=AttachFile&do=get&target=iwlwifi-6000g2a-ucode-17.168.5.3.tgz dest=/tmp/wlwifi-6000g2a-ucode-17.168.5.3.tgz

- name: unzip firmware
  shell: tar zxvf /tmp/wlwifi-6000g2a-ucode-17.168.5.3.tgz chdir=/tmp

- name: copy firmware
  copy: src=/tmp/iwlwifi-6000g2a-ucode-17.168.5.3/iwlwifi-6000g2a-5.ucode dest=/lib/firmware/iwlwifi-6000g2a-5.ucode

- name: load driver
  shell: modprobe -r iwlwifi && modprobe -v iwlwifi

- name: add repo for virtualbox
  shell: echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" > /etc/apt/sources.list.d/virtualbox.list

- name: install virtualbox
  apt: pkg=virtualbox-4.3 state=latest update_cache=yes 

- name: install xfce
  apt: pkg={{ item }} state=latest
  with_items:
   - xfce4
   - xfce4-goodies

- name: get extension
  shell: wget -P /tmp http://download.virtualbox.org/virtualbox/`VBoxManage -v| sed s/r.*$//g`/Oracle_VM_VirtualBox_Extension_Pack-`VBoxManage -v|sed s/r/-/g`.vbox-extpack 
  tags: extpack

- name: install it
  shell: VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-`VBoxManage -v|sed s/r/-/g`.vbox-extpack
  tags: extpack

- name: install flash player
  apt: pkg=flashplugin-nonfree state=latest 

- name: make fonts a bit smoother
  copy: src=_.fonts.conf dest=/etc/skel/.fonts.conf mode=644 
